spring:
  application:
    name: userregistrationsystem
  datasource:
    url: jdbc:mysql://localhost:3306/registration?createDatabaseIfNotExist=true
    username : root
    password : manager
  jpa:
    show-sql : true
    hibernate :
      ddl-auto : update

